import { useState } from 'react'
import { api } from '../lib/api'
import { DDMA_OFFICER_ID_PLACEHOLDER, recommendationContext, type DdmaDecisionKind } from '../lib/ddma'
import { useTickStore } from '../store/useTickStore'
import type { ActionCard, Announcement, AuditEvent, EscalationStage } from '../types/schemas'
import { MeshPropagationVisual } from './MeshPropagationVisual'

interface DecisionState {
  status: 'submitting' | 'done' | 'error'
  kind?: DdmaDecisionKind
  event?: AuditEvent
  announcement?: Announcement
  error?: string
}

/** The Government "Announce" workspace (new 5-item IA). Absorbs DdmaConsole.tsx's real
 * Approve/Modify/Reject flow (Task 14 retires that file): Approve/Modify now call the real
 * POST /api/announcements (Task 3/4) — approve + send through every simulated channel + record a
 * real DISSEMINATED audit event, all in one action, matching how the new IA collapses "approve"
 * and "disseminate" into a single Announce step. Reject still calls the existing
 * POST /api/ddma/decide (nothing to disseminate for a rejected card). */
export function AnnounceWorkspace() {
  const actionCards = useTickStore((s) => s.actionCards)
  const priorities = useTickStore((s) => s.priorities)
  const isolations = useTickStore((s) => s.isolations)
  const openAuditTrail = useTickStore((s) => s.openAuditTrail)

  const [officerId, setOfficerId] = useState(DDMA_OFFICER_ID_PLACEHOLDER)
  const [decisions, setDecisions] = useState<Record<string, DecisionState>>({})
  const [notesDraft, setNotesDraft] = useState<Record<string, string>>({})

  const decide = async (card: ActionCard, kind: DdmaDecisionKind) => {
    setDecisions((prev) => ({ ...prev, [card.alert_id]: { status: 'submitting' } }))
    const context = recommendationContext(card, priorities, isolations)
    const resolvedOfficerId = officerId.trim() || DDMA_OFFICER_ID_PLACEHOLDER
    try {
      if (kind === 'rejected') {
        const event = await api.submitDdmaDecision({
          action_card: card,
          officer_id: resolvedOfficerId,
          decision: 'rejected',
          notes: notesDraft[card.alert_id] ?? '',
        })
        setDecisions((prev) => ({ ...prev, [card.alert_id]: { status: 'done', kind, event } }))
      } else {
        const announcement = await api.sendAnnouncement({
          action_card: card,
          officer_id: resolvedOfficerId,
          recipient_count: context.population ?? 0,
          message: notesDraft[card.alert_id] || undefined,
        })
        setDecisions((prev) => ({ ...prev, [card.alert_id]: { status: 'done', kind, announcement } }))
      }
    } catch (err) {
      setDecisions((prev) => ({
        ...prev,
        [card.alert_id]: { status: 'error', error: err instanceof Error ? err.message : String(err) },
      }))
    }
  }

  return (
    <div className="flex-1 overflow-y-auto bg-slate-950 p-6">
      <div className="mb-4">
        <h1 className="text-xl font-bold">Announce</h1>
        <p className="text-sm text-slate-400">
          Approve or modify a recommendation to dispatch it for real over every simulated channel;
          reject to stand it down.
        </p>
      </div>

      <div className="mb-4 rounded border border-amber-500/40 bg-amber-500/10 px-4 py-3 text-sm text-amber-200">
        <span className="font-bold">No machine issues an evacuation order.</span> Every
        recommendation below was generated by the AI risk pipeline and requires a human DDMA
        officer to Approve, Modify, or Reject it before anything is disseminated.
      </div>

      <div className="mb-6 flex items-center gap-2 text-sm">
        <label htmlFor="announce-officer-id" className="text-slate-400">
          Officer ID
        </label>
        <input
          id="announce-officer-id"
          type="text"
          value={officerId}
          onChange={(event) => setOfficerId(event.target.value)}
          className="max-w-md flex-1 rounded border border-white/10 bg-white/5 px-2 py-1.5 font-mono text-xs text-slate-200"
        />
      </div>

      <div className="mb-6 rounded border border-white/10 bg-white/5 p-4">
        <MeshPropagationVisual />
      </div>

      <h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">
        Pending recommendations ({actionCards.length})
      </h2>

      {actionCards.length === 0 && (
        <p className="text-sm text-slate-500">No AI recommendations issued yet.</p>
      )}

      <ul className="space-y-3">
        {actionCards.map((card) => (
          <RecommendationRow
            key={card.alert_id}
            card={card}
            context={recommendationContext(card, priorities, isolations)}
            decision={decisions[card.alert_id]}
            notes={notesDraft[card.alert_id] ?? ''}
            onNotesChange={(value) => setNotesDraft((prev) => ({ ...prev, [card.alert_id]: value }))}
            onDecide={(kind) => void decide(card, kind)}
            onViewAuditTrail={() => openAuditTrail(card.alert_id)}
          />
        ))}
      </ul>
    </div>
  )
}

function RecommendationRow({
  card,
  context,
  decision,
  notes,
  onNotesChange,
  onDecide,
  onViewAuditTrail,
}: {
  card: ActionCard
  context: ReturnType<typeof recommendationContext>
  decision: DecisionState | undefined
  notes: string
  onNotesChange: (value: string) => void
  onDecide: (kind: DdmaDecisionKind) => void
  onViewAuditTrail: () => void
}) {
  const busy = decision?.status === 'submitting'
  const done = decision?.status === 'done'

  return (
    <li className="rounded border border-white/10 bg-white/5 p-4">
      <div className="mb-2 flex items-start justify-between gap-2">
        <div>
          <div className="flex items-center gap-2">
            <span className={`rounded px-2 py-0.5 text-xs font-bold ${stageBadgeClass(card.stage)}`}>
              {card.stage}
            </span>
            <span className="font-semibold">{card.headline}</span>
          </div>
          <p className="mt-0.5 text-xs text-slate-400">
            {card.village_id}
            {context.population !== null && ` · pop. ${context.population.toLocaleString()}`}
          </p>
        </div>
      </div>

      <p className="mb-2 text-sm text-slate-300">
        <span className="text-slate-500">AI rationale: </span>
        {card.reason_plain}
      </p>

      {!done && (
        <div className="mb-2">
          <textarea
            value={notes}
            onChange={(event) => onNotesChange(event.target.value)}
            placeholder="Message to send (defaults to the AI-generated rationale)"
            rows={2}
            className="w-full rounded border border-white/10 bg-white/5 px-2 py-1 text-xs text-slate-200"
          />
        </div>
      )}

      {!done && (
        <div className="flex items-center gap-2">
          <button
            type="button"
            disabled={busy}
            onClick={() => onDecide('approved')}
            className="rounded bg-emerald-600 px-3 py-1.5 text-sm font-semibold hover:bg-emerald-500 disabled:opacity-50"
          >
            Approve & Dispatch
          </button>
          <button
            type="button"
            disabled={busy}
            onClick={() => onDecide('modified')}
            className="rounded bg-amber-600 px-3 py-1.5 text-sm font-semibold text-black hover:bg-amber-500 disabled:opacity-50"
          >
            Modify & Dispatch
          </button>
          <button
            type="button"
            disabled={busy}
            onClick={() => onDecide('rejected')}
            className="rounded bg-red-700 px-3 py-1.5 text-sm font-semibold hover:bg-red-600 disabled:opacity-50"
          >
            Reject
          </button>
          {busy && <span className="text-xs text-slate-500">Submitting…</span>}
        </div>
      )}

      {decision?.status === 'error' && (
        <p className="mt-2 text-xs text-red-300">Could not submit decision: {decision.error}</p>
      )}

      {done && decision.announcement && (
        <div className="mt-2 rounded bg-black/20 px-3 py-2 text-xs">
          <p className="mb-1 font-semibold text-emerald-300">Dispatched for real.</p>
          {decision.announcement.channel_results.map((r) => (
            <p key={r.channel} className="text-slate-400">
              {r.channel}: {r.delivered_count}/{r.recipient_count} delivered, {r.acknowledged_count}{' '}
              acknowledged
            </p>
          ))}
          <button
            type="button"
            onClick={onViewAuditTrail}
            className="mt-1 rounded bg-white/10 px-2 py-1 font-semibold hover:bg-white/20"
          >
            View audit trail
          </button>
        </div>
      )}

      {done && decision.event && (
        <div className="mt-2 rounded bg-black/20 px-3 py-2 text-xs">
          <p className="text-slate-400">
            Rejected — stood down at {new Date(decision.event.t).toLocaleString()}
          </p>
          <button
            type="button"
            onClick={onViewAuditTrail}
            className="mt-1 rounded bg-white/10 px-2 py-1 font-semibold hover:bg-white/20"
          >
            View audit trail
          </button>
        </div>
      )}
    </li>
  )
}

function stageBadgeClass(stage: EscalationStage): string {
  switch (stage) {
    case 'RED':
      return 'bg-red-600'
    case 'ORANGE':
      return 'bg-orange-500'
    case 'YELLOW':
      return 'bg-yellow-500 text-black'
    default:
      return 'bg-emerald-600'
  }
}
