import type { Geometry } from 'geojson'
import type { CommanderResponseBlock, CommanderRoute, EvacuationRoute, RoadSegmentRisk, SettlementPriority, VillageIsolation } from '../types/schemas'
import { riskLevel } from '../lib/commander'
import { MapView } from './MapView'

const title = (value: unknown) => String(value ?? '').replaceAll('_', ' ')
const pct = (value: number) => `${Math.round(value * 100)}%`

function RiskGrid({ priorities }: { priorities: SettlementPriority[] }) {
  return <div className="commander-risk-grid">{priorities.slice(0, 6).map((item) => <article className={`commander-risk-card ${item.tier.toLowerCase()}`} key={item.village_id}><div className="commander-card-top"><span>{item.village_id}</span><strong>{item.tier === 'P1' ? 'CRITICAL' : item.tier === 'P2' ? 'HIGH' : 'ELEVATED'}</strong></div><div className="commander-risk-value">{pct(item.eps)}</div><p>Priority score · {Object.keys(item.components).slice(0, 2).map(title).join(' + ') || 'verified signals'}</p><button type="button" className="commander-link">View village →</button></article>)}</div>
}

function RoadGrid({ roads = [], isolations = [] }: { roads?: RoadSegmentRisk[]; isolations?: VillageIsolation[] }) {
  const impacted = roads.filter((road) => road.severed || road.p_blocked >= .45).slice(0, 6)
  return <div className="commander-road-list">{impacted.length ? impacted.map((road) => { const connected = isolations.filter((item) => item.severed_links.includes(road.edge_id)).map((item) => item.name).slice(0, 3); return <article className="commander-road-card" key={road.edge_id}><div><strong>{road.name || road.edge_id}</strong><span className="risk-pill high">{road.severed ? 'BLOCKED' : riskLevel(road.p_blocked)}</span></div><p>{road.is_bridge ? 'Bridge exposure' : 'Slope / rainfall exposure'} · {pct(road.p_blocked)} blockage probability</p><small>{connected.length ? `Connectivity impact: ${connected.join(', ')}` : 'Connectivity impact tracked in current feed'}</small></article> }) : <p className="commander-muted">No affected road segments in the current verified snapshot.</p>}</div>
}

function RouteCard({ item, onSave }: { item: CommanderRoute; onSave?: (item: CommanderRoute) => void }) {
  const route = item.route
  return <article className="commander-route-card"><div className="commander-card-top"><div><span className="eyebrow teal">RECOMMENDED ROUTE {item.route_rank}</span><h3>{route.shelter_name}</h3></div><span className="risk-pill low">LOWER RISK</span></div><div className="commander-route-metrics"><span><b>{(route.distance_m / 1000).toFixed(1)} km</b> distance</span><span><b>{route.est_walk_minutes} min</b> estimated</span><span><b>{route.shelter_capacity_ok ? 'Verified' : 'Check'}</b> destination</span></div><p>{item.safety_reason}</p>{item.risk_snapshot.map((risk) => <small key={risk}>{risk}</small>)}<div className="commander-actions">{onSave && <button type="button" className="commander-secondary" onClick={() => onSave(item)}>Save plan</button>}<button type="button" className="commander-secondary">View route</button></div></article>
}

function ShelterGrid({ shelters }: { shelters: EvacuationRoute[] }) { return <div className="commander-shelter-grid">{shelters.slice(0, 6).map((shelter) => <article className="commander-shelter-card" key={`${shelter.shelter_id}-${shelter.village_id}`}><span className="eyebrow teal">SHELTER DESTINATION</span><h3>{shelter.shelter_name}</h3><strong>{(shelter.distance_m / 1000).toFixed(1)} km</strong><p>{shelter.est_walk_minutes} min estimated walk · capacity status {shelter.shelter_capacity_ok ? 'verified' : 'requires check'}</p><button type="button" className="commander-link">View on map →</button></article>)}</div> }

export function CommanderResponse({ blocks, onSave, onAnnounce, onWhatIf }: { blocks: CommanderResponseBlock[]; onSave?: (item: CommanderRoute) => void; onAnnounce: () => void; onWhatIf: () => void }) {
  return <div className="commander-response-content">{blocks.map((block, index) => { const data = block.data; if (block.type === 'text') return <p className="commander-response-text" key={index}>{String(data.text)}</p>; if (block.type === 'map') return <div className="commander-response-map" key={index}><MapView routeGeometry={(data.routeGeometry as Geometry | null) ?? null} /></div>; if (block.type === 'risk') return <RiskGrid key={index} priorities={(data.priorities as SettlementPriority[]) ?? []}/>; if (block.type === 'road') return <RoadGrid key={index} roads={(data.roads as RoadSegmentRisk[]) ?? []} isolations={(data.isolations as VillageIsolation[]) ?? []}/>; if (block.type === 'route') return <RouteCard key={index} item={data as unknown as CommanderRoute} onSave={onSave}/>; if (block.type === 'shelter') return <ShelterGrid key={index} shelters={(data.shelters as EvacuationRoute[]) ?? []}/>; if (block.type === 'evidence') return <aside className="commander-evidence" key={index}><div className="commander-card-top"><strong>{String(data.title)}</strong><span className="confidence">{String(data.confidence)}</span></div><ul>{((data.factors as string[]) ?? []).map((factor) => <li key={factor}>{factor}</li>)}</ul></aside>; if (block.type === 'action') return <aside className="commander-action-panel" key={index}><span className="eyebrow amber">HUMAN REVIEW REQUIRED</span><h3>{String(data.title)}</h3><p>{String(data.text)}</p><div className="commander-actions"><button type="button" className="commander-primary" onClick={onAnnounce}>Review announcement</button><button type="button" className="commander-secondary" onClick={onWhatIf}>Run What-if</button></div></aside>; return null })}</div>
}
