import { useState } from 'react'
import { api } from '../lib/api'
import { DDMA_OFFICER_ID_PLACEHOLDER, recommendationContext, type DdmaDecisionKind } from '../lib/ddma'
import { useTickStore } from '../store/useTickStore'
import type { ActionCard, AuditEvent, EscalationStage } from '../types/schemas'

interface DecisionState {
  status: 'submitting' | 'done' | 'error'
  kind?: DdmaDecisionKind
  event?: AuditEvent
  error?: string
}

/**
 * BUILD_PLAN.md task 3.7 — the DDMA Console: "pending recommendations queue, each showing the AI
 * rationale, EPS breakdown, affected population, and Approve / Modify / Reject buttons.
 * Human-in-the-loop must be visually obvious — a judge should see that no machine ordered an
 * evacuation."
 *
 * **Scope ruling (documented, this task's own choice (a)):** `audit/producers.py`'s
 * `record_ddma_decision()` already did the real accountable-decision work (task 3.6) but had no
 * REST route calling it. This session adds `POST /api/ddma/decide` (`backend/app/api/routes.py`)
 * — a small, well-scoped wiring task, not a reimplementation — so Approve/Modify/Reject below are
 * REAL end-to-end actions: they call the real backend, which appends a real `DDMA_APPROVED` (or
 * `STOOD_DOWN`, for Reject) event onto the real hash-chained `AuditLog`, verifiable immediately
 * afterwards via "View audit trail" (task 3.8, `AuditTrailView.tsx`) or `GET /api/audit/{alert_id}`
 * directly. This is choice (a) from the task's own two offered options, not the honest-disabled
 * fallback (b) — the backend addition was small enough not to need it.
 *
 * The pending queue is `useTickStore.actionCards` — the real `ActionCard`s this AOI's pipeline
 * has issued (currently via `decision/stub.py`, ORANGE/RED settlements only — see
 * BUILD_PLAN.md's own Phase 3 note that `decision/stub.py` "goes away" once escalation.py/
 * action_card.py are wired into `pipeline.py`, a separate, later integration task). Nothing here
 * fabricates a recommendation that wasn't actually issued by the pipeline.
 *
 * No officer login/credential system exists anywhere in this codebase — `officer_id` is a plain,
 * clearly-labelled placeholder text field (`lib/ddma.ts::DDMA_OFFICER_ID_PLACEHOLDER`), never
 * presented as a real DDMA identity, per CLAUDE.md's explicit rule against inventing one.
 */
export function DdmaConsole({ onBack }: { onBack: () => void }) {
  const actionCards = useTickStore((s) => s.actionCards)
  const priorities = useTickStore((s) => s.priorities)
  const isolations = useTickStore((s) => s.isolations)
  const openAuditTrail = useTickStore((s) => s.openAuditTrail)

  const [officerId, setOfficerId] = useState(DDMA_OFFICER_ID_PLACEHOLDER)
  const [decisions, setDecisions] = useState<Record<string, DecisionState>>({})
  const [notesDraft, setNotesDraft] = useState<Record<string, string>>({})

  const submit = async (card: ActionCard, kind: DdmaDecisionKind) => {
    setDecisions((prev) => ({ ...prev, [card.alert_id]: { status: 'submitting' } }))
    try {
      const event = await api.submitDdmaDecision({
        action_card: card,
        officer_id: officerId.trim() || DDMA_OFFICER_ID_PLACEHOLDER,
        decision: kind,
        notes: notesDraft[card.alert_id] ?? '',
      })
      setDecisions((prev) => ({ ...prev, [card.alert_id]: { status: 'done', kind, event } }))
    } catch (err) {
      setDecisions((prev) => ({
        ...prev,
        [card.alert_id]: { status: 'error', error: err instanceof Error ? err.message : String(err) },
      }))
    }
  }

  return (
    <div className="flex h-full flex-col overflow-y-auto bg-slate-950 p-6">
      <div className="mb-4 flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold">DDMA Console</h1>
          <p className="text-sm text-slate-400">District Disaster Management Authority</p>
        </div>
        <button
          type="button"
          onClick={onBack}
          className="rounded bg-white/10 px-3 py-1.5 text-sm font-semibold hover:bg-white/20"
        >
          ← Back to map
        </button>
      </div>

      {/* CLAUDE.md rule 9 / task 3.7: human-in-the-loop must be VISUALLY OBVIOUS. */}
      <div className="mb-4 rounded border border-amber-500/40 bg-amber-500/10 px-4 py-3 text-sm text-amber-200">
        <span className="font-bold">No machine issues an evacuation order.</span> Every
        recommendation below was generated by the AI risk pipeline and requires a human DDMA
        officer to Approve, Modify, or Reject it before anything is disseminated.
      </div>

      <div className="mb-6 flex items-center gap-2 text-sm">
        <label htmlFor="ddma-officer-id" className="text-slate-400">
          Officer ID
        </label>
        <input
          id="ddma-officer-id"
          type="text"
          value={officerId}
          onChange={(event) => setOfficerId(event.target.value)}
          className="flex-1 max-w-md rounded border border-white/10 bg-white/5 px-2 py-1.5 font-mono text-xs text-slate-200"
        />
        <span className="text-xs text-slate-500">
          Placeholder — no real DDMA login/credential system exists yet.
        </span>
      </div>

      <h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">
        Pending recommendations ({actionCards.length})
      </h2>

      {actionCards.length === 0 && (
        <p className="text-sm text-slate-500">
          No AI recommendations issued yet — action cards are only generated once a settlement
          reaches ORANGE or RED (BUILD_PLAN.md §4 escalation stages).
        </p>
      )}

      <ul className="space-y-3">
        {actionCards.map((card) => (
          <RecommendationRow
            key={card.alert_id}
            card={card}
            context={recommendationContext(card, priorities, isolations)}
            decision={decisions[card.alert_id]}
            notes={notesDraft[card.alert_id] ?? ''}
            onNotesChange={(value) =>
              setNotesDraft((prev) => ({ ...prev, [card.alert_id]: value }))
            }
            onDecide={(kind) => void submit(card, kind)}
            onViewAuditTrail={() => openAuditTrail(card.alert_id)}
          />
        ))}
      </ul>
    </div>
  )
}

function RecommendationRow({
  card,
  context,
  decision,
  notes,
  onNotesChange,
  onDecide,
  onViewAuditTrail,
}: {
  card: ActionCard
  context: ReturnType<typeof recommendationContext>
  decision: DecisionState | undefined
  notes: string
  onNotesChange: (value: string) => void
  onDecide: (kind: DdmaDecisionKind) => void
  onViewAuditTrail: () => void
}) {
  const busy = decision?.status === 'submitting'
  const done = decision?.status === 'done'

  return (
    <li className="rounded border border-white/10 bg-white/5 p-4">
      <div className="mb-2 flex items-start justify-between gap-2">
        <div>
          <div className="flex items-center gap-2">
            <span className={`rounded px-2 py-0.5 text-xs font-bold ${stageBadgeClass(card.stage)}`}>
              {card.stage}
            </span>
            <span className="font-semibold">{card.headline}</span>
          </div>
          <p className="mt-0.5 text-xs text-slate-400">
            {card.village_id}
            {context.population !== null && ` · pop. ${context.population.toLocaleString()}`}
            {context.isolatedNow !== null && (context.isolatedNow ? ' · isolated' : '')}
          </p>
        </div>
        {context.tier && (
          <span className={`rounded px-2 py-0.5 text-xs font-bold ${tierBadgeClass(context.tier)}`}>
            {context.tier}
          </span>
        )}
      </div>

      <p className="mb-2 text-sm text-slate-300">
        <span className="text-slate-500">AI rationale: </span>
        {card.reason_plain}
      </p>

      {context.eps !== null && (
        <div className="mb-2">
          <p className="text-xs text-slate-500">EPS {context.eps.toFixed(2)} breakdown</p>
          {Object.keys(context.components).length === 0 ? (
            <p className="text-xs text-slate-600">No component breakdown reported.</p>
          ) : (
            <ul className="mt-1 space-y-1">
              {Object.entries(context.components).map(([key, value]) => (
                <li key={key}>
                  <div className="flex items-center justify-between text-[11px] text-slate-500">
                    <span>{key}</span>
                    <span>{value.toFixed(2)}</span>
                  </div>
                  <div className="h-1 w-full overflow-hidden rounded bg-white/10">
                    <div
                      className="h-full bg-emerald-500"
                      style={{ width: `${Math.max(0, Math.min(1, value)) * 100}%` }}
                    />
                  </div>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}

      {!done && (
        <div className="mb-2">
          <textarea
            value={notes}
            onChange={(event) => onNotesChange(event.target.value)}
            placeholder="Notes (required if modifying the recommendation)"
            rows={2}
            className="w-full rounded border border-white/10 bg-white/5 px-2 py-1 text-xs text-slate-200"
          />
        </div>
      )}

      {!done && (
        <div className="flex items-center gap-2">
          <button
            type="button"
            disabled={busy}
            onClick={() => onDecide('approved')}
            className="rounded bg-emerald-600 px-3 py-1.5 text-sm font-semibold hover:bg-emerald-500 disabled:opacity-50"
          >
            Approve
          </button>
          <button
            type="button"
            disabled={busy || notes.trim().length === 0}
            title={notes.trim().length === 0 ? 'Add a note describing the modification first' : undefined}
            onClick={() => onDecide('modified')}
            className="rounded bg-amber-600 px-3 py-1.5 text-sm font-semibold text-black hover:bg-amber-500 disabled:opacity-50"
          >
            Modify
          </button>
          <button
            type="button"
            disabled={busy}
            onClick={() => onDecide('rejected')}
            className="rounded bg-red-700 px-3 py-1.5 text-sm font-semibold hover:bg-red-600 disabled:opacity-50"
          >
            Reject
          </button>
          {busy && <span className="text-xs text-slate-500">Submitting…</span>}
        </div>
      )}

      {decision?.status === 'error' && (
        <p className="mt-2 text-xs text-red-300">Could not submit decision: {decision.error}</p>
      )}

      {done && decision.event && (
        <div className="mt-2 flex items-center justify-between rounded bg-black/20 px-3 py-2 text-xs">
          <span className={decisionResultClass(decision.kind)}>
            {decisionResultLabel(decision.kind)} — recorded as{' '}
            <span className="font-mono">{decision.event.kind}</span> at{' '}
            {new Date(decision.event.t).toLocaleString()}
          </span>
          <button
            type="button"
            onClick={onViewAuditTrail}
            className="rounded bg-white/10 px-2 py-1 font-semibold hover:bg-white/20"
          >
            View audit trail
          </button>
        </div>
      )}
    </li>
  )
}

function decisionResultLabel(kind: DdmaDecisionKind | undefined): string {
  switch (kind) {
    case 'approved':
      return 'Approved'
    case 'modified':
      return 'Approved (modified)'
    case 'rejected':
      return 'Rejected — stood down'
    default:
      return 'Decided'
  }
}

function decisionResultClass(kind: DdmaDecisionKind | undefined): string {
  return kind === 'rejected' ? 'text-slate-400' : 'text-emerald-300'
}

function tierBadgeClass(tier: 'P1' | 'P2' | 'P3'): string {
  switch (tier) {
    case 'P1':
      return 'bg-red-600'
    case 'P2':
      return 'bg-orange-500'
    default:
      return 'bg-slate-600'
  }
}

function stageBadgeClass(stage: EscalationStage): string {
  switch (stage) {
    case 'RED':
      return 'bg-red-600'
    case 'ORANGE':
      return 'bg-orange-500'
    case 'YELLOW':
      return 'bg-yellow-500 text-black'
    default:
      return 'bg-emerald-600'
  }
}
