import type { FeatureCollection, Point } from 'geojson'
import { MapLibreMap, type GeoJSONSource } from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'
import { useEffect, useRef, useState } from 'react'
import type { CellRisk, RoadSegmentRisk, VillageIsolation } from '../types/schemas'
import { cellRisksToFeatureCollection } from '../lib/grid'
import { roadRisksToFeatureCollection } from '../lib/roads'
import { stubVillagePosition } from '../lib/villages'
import { STAGE_COLOR } from '../lib/escalation'

type Selection = { type:'cell'|'road'|'village'; id:string }
type Props = { cells:CellRisk[]; roads:RoadSegmentRisk[]; villages:VillageIsolation[]; onSelect:(selection:Selection)=>void }
const CENTER:[number,number] = [92.7173,23.7307]
const empty:FeatureCollection = {type:'FeatureCollection',features:[]}

export function SimulatorMap({cells,roads,villages,onSelect}:Props) {
  const container = useRef<HTMLDivElement|null>(null); const mapRef = useRef<MapLibreMap|null>(null); const callback = useRef(onSelect)
  const [layers,setLayers] = useState({cells:true,roads:true,villages:true,fault:false,routes:false})
  useEffect(()=>{ callback.current=onSelect },[onSelect])
  useEffect(()=>{ if(!container.current||mapRef.current||typeof window.WebGLRenderingContext==='undefined')return; const map=new MapLibreMap({container:container.current,center:CENTER,zoom:12.3,minZoom:8,maxZoom:18,attributionControl:false,style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'background',type:'background',paint:{'background-color':'#dce8e2'}},{id:'osm',type:'raster',source:'osm',paint:{'raster-opacity':.83,'raster-saturation':-.32,'raster-contrast':-.08}}]}}); mapRef.current=map; const resize=new ResizeObserver(()=>map.resize()); resize.observe(container.current); map.on('load',()=>{map.addSource('risk',{type:'geojson',data:empty});map.addLayer({id:'risk-fill',type:'fill',source:'risk',paint:{'fill-color':['get','color'],'fill-opacity':.3,'fill-outline-color':['get','color']}});map.addSource('roads',{type:'geojson',data:empty});map.addLayer({id:'roads-line',type:'line',source:'roads',layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':['get','color'],'line-width':['case',['get','severed'],5,3],'line-opacity':.95,'line-dasharray':['case',['get','severed'],['literal',[2,1]],['literal',[1,0]]]}});map.addSource('villages',{type:'geojson',data:empty});map.addLayer({id:'villages-point',type:'circle',source:'villages',paint:{'circle-radius':['interpolate',['linear'],['zoom'],8,5,15,9],'circle-color':['get','color'],'circle-stroke-color':'#ffffff','circle-stroke-width':2}}); map.on('click','risk-fill',e=>{const id=e.features?.[0]?.properties?.cell_id;if(typeof id==='string')callback.current({type:'cell',id})});map.on('click','roads-line',e=>{const id=e.features?.[0]?.properties?.edge_id;if(typeof id==='string')callback.current({type:'road',id})});map.on('click','villages-point',e=>{const id=e.features?.[0]?.properties?.village_id;if(typeof id==='string')callback.current({type:'village',id})});for(const id of ['risk-fill','roads-line','villages-point']){map.on('mouseenter',id,()=>{map.getCanvas().style.cursor='pointer'});map.on('mouseleave',id,()=>{map.getCanvas().style.cursor=''})}}); return()=>{resize.disconnect();try{map.remove()}catch{/* WebGL can be unavailable in test DOM */}mapRef.current=null}},[])
  useEffect(()=>{const map=mapRef.current;if(!map||!map.isStyleLoaded())return;const villageFeatures:FeatureCollection<Point>={type:'FeatureCollection',features:villages.map(v=>{const p=v.geometry?.type==='Point'?{lat:v.geometry.coordinates[1],lon:v.geometry.coordinates[0]}:stubVillagePosition(v.village_id,{lat:23.7307,lon:92.7173});return{type:'Feature',geometry:{type:'Point',coordinates:[p.lon,p.lat]},properties:{village_id:v.village_id,color:v.isolated_now?'#e75259':'#e3ad4f'}}})};(map.getSource('risk') as GeoJSONSource|undefined)?.setData(cells.length?cellRisksToFeatureCollection(cells,{lat:23.7307,lon:92.7173}):empty);(map.getSource('roads') as GeoJSONSource|undefined)?.setData(roads.length?roadRisksToFeatureCollection(roads,{lat:23.7307,lon:92.7173}):empty);(map.getSource('villages') as GeoJSONSource|undefined)?.setData(villageFeatures)},[cells,roads,villages])
  useEffect(()=>{const map=mapRef.current;if(!map||!map.isStyleLoaded())return;const visible=(v:boolean)=>v?'visible':'none';map.setLayoutProperty('risk-fill','visibility',visible(layers.cells));map.setLayoutProperty('roads-line','visibility',visible(layers.roads));map.setLayoutProperty('villages-point','visibility',visible(layers.villages))},[layers])
  const toggle=(key:keyof typeof layers)=>setLayers(s=>({...s,[key]:!s[key]})); const reset=()=>mapRef.current?.flyTo({center:CENTER,zoom:12.3,duration:500});
  return <div className="sim-map-shell"><div ref={container} className="sim-map-canvas"/><div className="map-overlay-title"><span className="eyebrow">PREDICTIVE GIS VIEW</span><strong>Aizawl operational area</strong><small>Scenario output · click any cell, road, or settlement</small></div><div className="map-status-pill"><i/> SIMULATION · DEMO DATA</div><div className="sim-map-tools"><button onClick={()=>mapRef.current?.zoomIn()} aria-label="Zoom in">+</button><button onClick={()=>mapRef.current?.zoomOut()} aria-label="Zoom out">−</button><button onClick={reset} aria-label="Reset map view">⌖</button><button onClick={()=>toggle('fault')} aria-pressed={layers.fault}>⌁</button><button onClick={()=>toggle('routes')} aria-pressed={layers.routes}>⇢</button></div><div className="sim-layer-control"><span>LAYERS</span>{Object.entries({cells:'Risk grid',roads:'Road network',villages:'Settlements',fault:'Fault buffer',routes:'Safe route'}).map(([key,label])=><label key={key}><input type="checkbox" checked={layers[key as keyof typeof layers]} onChange={()=>toggle(key as keyof typeof layers)}/> {label}</label>)}</div><div className="sim-legend"><b>RISK</b><span><i style={{background:STAGE_COLOR.GREEN}}/>Low</span><span><i style={{background:STAGE_COLOR.YELLOW}}/>Moderate</span><span><i style={{background:STAGE_COLOR.ORANGE}}/>High</span><span><i style={{background:STAGE_COLOR.RED}}/>Critical</span><hr/><b>NETWORK</b><span><em className="line-normal"/>Normal</span><span><em className="line-risk"/>At risk</span><span><em className="line-cut"/>Severed</span></div></div>
}
